# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(547, 259)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_advertisementID = QtWidgets.QLabel(self.centralwidget)
        self.lbl_advertisementID.setGeometry(QtCore.QRect(20, 20, 531, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lbl_advertisementID.setFont(font)
        self.lbl_advertisementID.setObjectName("lbl_advertisementID")
        self.btn_send = QtWidgets.QPushButton(self.centralwidget)
        self.btn_send.setGeometry(QtCore.QRect(190, 180, 171, 41))
        self.btn_send.setObjectName("btn_send")
        self.txt_advertisementID = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_advertisementID.setGeometry(QtCore.QRect(112, 90, 341, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.txt_advertisementID.setFont(font)
        self.txt_advertisementID.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_advertisementID.setObjectName("txt_advertisementID")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sahibinden.com Fotoğraf İndirme Aracı"))
        self.lbl_advertisementID.setText(_translate("MainWindow", "İndirmek İstediğiniz İlanın İlan Numarasını Giriniz :"))
        self.btn_send.setText(_translate("MainWindow", "İndir"))
